final List<String> aliimran = [
  "1.	Elif, Lâm, Mîm.",
  "2.	Allah... İlâh yok O'ndan başka... Hayy'dır O, Kayyûm'dur.",
  "3.	O, sana Kitap'ı, önündekileri tasdikleyici olarak hak bir yoldan indirdi. Tevrat'ı ve İncil'i de indirmişti.",
  "4.	Daha önce insanlara bir yol gösterici olarak Furkan'ı da indirdi. Şu bir gerçek ki, Allah'ın ayetlerini örtüp inkâr edenler için şiddetli bir azap vardır. Ve Allah hem Azîz'dir hem intikam alıcı...",
  "5.	Allah... Gökte ve yerde hiçbir şey O'na gizli kalmaz.",
  "6.	Rahimlerde sizi dilediğince şekillendiren O'dur. İlâh yok O'ndan başka. Azîz'dir O, Hakîm'dir.",
  "7.	Kitap'ı sana indiren O'dur: Onun ayetlerinden bir kısmı muhkemlerdir ki; onlar Kitap'ın anasıdır. Diğer ayetlerse müteşâbihlerdir. Şu var ki, kalplerinde bir eğrilik ve bozukluk bulunanlar, fitne aramak, onun teviline öncelik tanımak için Kitap'ın sadece müteşâbih kısmının ardına düşerler. Onun tevilini ise bir Allah bilir, bir de ilimde derinleşmiş olanlar. Bunlar, \"Ona inandık, hepsi Rabbimizin katındandır.\" derler. Gönül ve akıl sahiplerinden başkası gereğince düşünemez.",
  "8.	Ey Rabbimiz! Bizi doğruya ve güzele yönelttikten sonra kalplerimizi bozup eğriltme ve bize katından bir rahmet bağışla! Sen, yalnız sen Vahhâb'sın, bol bol bağışta bulunansın.",
  "9.	Ey Rabbimiz! Sen Câmî'sin; insanları varlığında kuşku bulunmayan bir günde mutlaka toplayacaksın. Allah, sözünü yerine getireceği yer ve zamanı asla şaşırmaz.",
  "10.	Küfre sapanlara gelince, onların malları da çocukları da Allah'a karşı kendilerine hiçbir yarar sağlamayacaktır. Onlar, işte onlar, ateşin yakıtıdırlar.",
  "11.	Tıpkı Firavun hanedanı ve onlardan öncekilerin durumu gibi. Ayetlerimizi yalanlamışlardı da Allah, onları günahları yüzünden yakalamıştı. Allah, cezayı çok şiddetli vermektedir.",
  "12.	De o küfre sapanlara: \"Yenileceksiniz ve cehenneme sürüleceksiniz. Ne kötü döşektir o!\"",
  "13.	Yüz yüze gelen şu iki toplulukta sizin için bir ibret vardır: Biri Allah yolunda çarpışıyordu; ötekisi küfre batmıştı. Allah yolunda çarpışanları, kafa gözleriyle kendilerinin iki katı görüyorlardı. Allah, öz yardımıyla dilediğini destekler. İşte bunda, gözleri olanlar için gerçek bir ibret vardır.",
  "14.	Kadınlara, oğullara, altın ve gümüşten oluşturulmuş yığınlara, salma atlara, davarlara ve ekinlere tutkunlukların sevgisi, insanlar için süslenip püslenmiştir. Tüm bunlar geçici-iğreti hayatın nimetidir. Allah'a gelince, varılacak yerin en güzeli onun yanındadır.",
  "15.	De ki: \"Bu sayılanlardan daha iyisini size haber vereyim mi? Sakınıp korunanlar için, Rableri katında, altlarından nehirler akan, içinde sürekli kalacakları cennetler, tertemiz eşler ve Allah'tan bir hoşnutluk olacaktır. Allah, kulları en iyi biçimde görmektedir.\"",
  "16.	Kullar ki, şöyle derler: \"Ey Rabbimiz, kuşkusuz olarak sana inandık. Bağışla günahlarımızı, ateş azabından koru bizi!\"",
  "17.	Kullar ki, sabredenlerdir, özü-sözü doğru olanlardır, ilahî huzurda duranlardır, nimet ve imkânlardan başkalarını yararlandıranlardır; seherlerde, bağışlanmak için yakaranlardır.",
  "18.	Allah, kendisinden başka tanrı olmadığına tanıktır. Meleklerle ilim sahipleri de adalet ölçüsüne sarılarak tanıklık etmişlerdir ki, o Azîz ve Hakîm olandan başka hiçbir ilah yoktur.",
  "19.	Allah katında din İslam'dır/barış ve esenlik için Allah'a teslim olmaktır. Kitap verilmiş olanlar, kendilerine ilim geldikten sonra, aralarındaki kıskançlık/doymazlık/azgınlık/denge noktasından sapma/yalancılık/zulüm/kibir/zinakârlık yüzünden ihtilafa düştü. Kim Allah'ın ayetlerine nankörlük/Allah'ın ayetlerini inkâr ederse, Allah, hesabı çabucak görecektir.",
  "20.	Seninle kanıt yarıştırmaya girerlerse şöyle söyle: \"Ben yüzümü Allah'a teslim ettim. Bana uyanlar da.\" Kitap verilenlerle ümmîlere de sor: \"Siz de teslim oldunuz mu?\" Eğer teslim olurlarsa doğruya ve güzele kılavuzlanmışlardır. Yüz çeviririlerse sana düşen sadece tebliğ etmektir. Allah, kullarını görmektedir.",
  "21.	Allah'ın ayetlerini inkâr edip haksız yere peygamberleri öldürenler ve insanlar içinden adaletle emredenlerin canına kıyanlar var ya, işte onlara korkunç bir azabı muştula.",
  "22.	Çalışıp ürettikleri hem dünyada hem de âhirette boşa çıkmıştır. Hiçbir yardımcıları da yoktur onların.",
  "23.	Şu kendilerine kitaptan bir pay verilmiş olanlara bak, aralarında hüküm vermesi için Allah'ın kitabına çağırılıyorlar da içlerinden bir zümre yüz çevirerek dönüp gidiyor.",
  "24.	Bunun sebebi onların, \"Ateş bize sayılı birkaç gün dışında asla dokunmayacaktır\" demeleridir. Uydurmuş oldukları yalanlar, dinlerinde kendilerini aldatmaktadır.",
  "25.	Peki, o kendisinde kuşku bulunmayan günde, onları bir araya topladığımız vakit halleri nice olacak! O gün her benlik, kazandığının karşılığını tam almıştır. Onlar, hiçbir zulme uğratılmazlar.",
  "26.	Şöyle yakar: \"Ey mülkün/saltanatın Mâlik'i/sahibi olan Allahım! Sen mülkü/saltanatı dilediğine verir, mülkü/ saltanatı dilediğinden çekip alırsın. Dilediğini yüceltip aziz edersin, dilediğini alçaltıp zelil kılarsın. İmkân, mal ve nimet senin elindedir. Sen, her şeye kadirsin.\"",
  "27.	\"Geceyi gündüzün içine sokarsın, gündüzü de gecenin içine sokarsın. Diriyi ölüden çıkarırsın, ölüyü diriden çıkarırsın. Dilediğini hesapsızca rızıklandırırsın.\"",
  "28.	Müminler, müminleri bırakıp da küfre sapanları gönül dostu edinmesinler. Kim bunu yaparsa Allah'la ilişiği kesilir. Ancak bir sakınma ile onlardan korunmanız müstesna. Allah sizi kendisinden sakınmaya çağırır. Ve dönüş yalnız Allah'adır.",
  "29.	De ki: \"Göğüslerinizde olanı gizleseniz de açıklasanız da Allah onu bilir. Göklerdekileri, yerdekileri de bilir. Allah her şeye Kadîr'dir.\"",
  "30.	Gün gelecek, her benlik, hayırdan işlediğini önünde bulacaktır. Kötülükten işlediğini de... İsteyecektir ki, önüne getirilenle kendisi arasında uzun bir mesafe olsun. Allah sizi, kendisinden sakınmaya çağırır. Allah, kullarına karşı Raûf'tur, çok şefkatlidir.",
  "31.	De ki: \"Eğer Allah'ı seviyorsanız bana uyun ki, Allah da sizi sevsin ve günahlarınızı bağışlasın. Allah çok affedici, çok merhametlidir.\"",
  "32.	Şunu da söyle: \"Allah'a ve resule itaat edin.\" Eğer yüz çevirirlerse, Allah küfre sapanları sevmez.",
  "33.	Allah; Âdem'i, Nûh'u, İbrahim Ailesi'ni, İmran Ailesi'ni seçerek âlemlere üstün kılmıştır;",
  "34.	Birbirinden gelen soylar halinde. Allah, hakkıyla işiten, gereğince bilendir.",
  "35.	Hani, İmran'ın karısı şöyle demişti: \"Rabbim, karnımdakini özgür bir biçimde sana adadım; onu benden kabul et! Kuşkusuz,sen, evet sen, her şeyi duyan, her şeyi bilensin!\"",
  "36.	Onu doğurunca -Allah onun ne doğurduğunu daha iyi bildiği halde- şöyle dedi: \"Rabbim, onu kız olarak doğurdum ve erkek, kız gibi değildir. Adını Meryem koydum onun. Onu ve soyunu, kovulmuş şeytandan sana sığındırıyorum!\"",
  "37.	Allah, onu güzel bir kabulle kabul etti ve onu güzel bir bitki gibi besleyip büyüttü. Onu, Zekeriyya'nın korumasına verdi. Zekeriyya, mihrapta onun yanına her girdiğinde, orada bir rızık bulur ve sorardı: \"Meryem, bu sana nereden?\" Meryem de \"Bu, Allah katındandır; çünkü Allah dilediğini hesapsızca rızıklandırır.\" derdi.",
  "38.	Zekeriyya orada Rabbine yakarmıştı: \"Rabbim, demişti, katından bana tertemiz bir soy bağışla!Sen yakarışı en iyi duyansın!\"",
  "39.	Zekeriyya mihrapta durmuş dua ederken/namaz kılarken, melekler ona şöyle çağırmıştı: \"Allah sana, Allah'tan bir kelimeyi doğrulayıcı bir efendi; nefsine egemen bir benlik, hayır ve barışı sevenlerden bir peygamber olarak Yahya'yı müjdeliyor.\"",
  "40.	Dedi ki: \"Rabbim, benim nasıl çocuğum olur? İhtiyarlık tam bir biçimde üstüme binmiş, karım ise kısır!\" Allah cevap verdi: \"Allah, dilediği şeyi işte böyle yapar!\"",
  "41.	Zekeriyya dedi: \"Rabbim,bana bir belirti ver!\" Allah buyurdu: \"Sana belirti şudur: \"İnsanlarla üç gün, işaretleşme dışında konuşmayacaksın. Rabbini çok an. Akşam-sabah tespih et!\"",
  "42.	Bir de melekler şöyle demişlerdi: \"Ey Meryem, Allah seni seçti. Seni tertemiz kıldı ve seni âlemlerin kadınları üstüne yüceltti.\"",
  "43.	\"Ey Meryem, Rabbinin huzurunda saygıyla el bağla. Secdeye kapan ve rükû edenlerle birlikte rükû et!\"",
  "44.	Bu, gayb haberlerindendir ki, sana vahyediyoruz. Onlar, Meryem'in bakımını kimin üstleneceğini belirlemek için kalemlerini atarlarken sen yanlarında değildin. Çekiştikleri sırada da yanlarında değildin.",
  "45.	Bir de, melekler şöyle demişti: \"Ey Meryem! Allah seni, kendisinden bir kelimeyle muştuluyor. Adı, Meryem'in oğlu İsa Mesih'tir.Dünya ve âhirette yüz akıdır.Allah'a yaklaştırılanlardandır.\"",
  "46.	\"Beşikte ve yetişkin çağında insanlarla konuşacaktır. Barışa ve hayra yönelik iş yapanlardandır.\"",
  "47.	Meryem dedi ki: \"Rabbim, çocuğum nasıl olur benim? Bana hiçbir insan dokunmadı ki!\" Allah cevap verdi: \"Allah dilediğini işte böyle yaratır! Bir iş ve oluşa karar verdiğinde sadece ona \"Ol!\" der; ve o hemen oluverir.\"",
  "48.	Ona Kitap'ı, hikmeti, Tevrat'ı ve İncil'i öğretecek.",
  "49.	Onu Beniisrail'e şöyle konuşan bir resul yapacak: \"Şu bir gerçek ki, ben size Rabbinizden bir mucize getirdim: Ben, çamurdan, kuş görünümünde bir şey yapar, ona üflerim de Allah'ın izniyle kuş oluverir. Ben, körü ve abraşı iyileştirir, ölüleri Allah'ın izniyle diriltirim. Evlerinizde yemekte ve biriktirmekte olduklarınızı size haber veririm. Eğer inananlarsanız, bunda sizin için tam bir mucize vardır.\"",
  "50.	\"Tevrat'tan önümde bulunanı doğrulayıcıyım. Size haram kılınmış olanın bir kısmını size helal yapacağım. Rabbinizden bir mucize getirdim size. Artık Allah'tan sakının ve bana itaat edin!\"",
  "51.	\"Allah benim de Rabbimdir, sizin de Rabbinizdir; o halde, O'na kulluk edin!İşte bu, dosdoğru bir yoldur.\"",
  "52.	İsa onlardan inkârı sezince şöyle konuştu: \"Allah'a gidişte benim yardımcılarım kim?\" Havâriler dediler ki: \"Biz Allah'ın yardımcılarıyız!Allah'a iman ettik biz!Tanık ol, biz müslümanlarız/Allah'a teslim olanlarız.\"",
  "53.	\"Ey Rabbimiz! Senin indirdiğine iman ettik, resule uyduk; artık bizi gerçeğin tanıklarıyla beraber yaz!\"",
  "54.	Onlar tuzak kurdular, Allah da tuzak kurdu. Ve Allah, tuzak kuranların en hayırlısıdır.",
  "55.	Allah şunu da demişti: \"Ey İsa, senin canını alacağım, seni kendime yükselteceğim; seni, inkâr edenlerden uzaklaştırıp arındıracağım. Ve sana uyanları, inkâr edenlerin, kıyamete kadar üstünde tutacağım. Sonra bana olacak dönüşünüz; tartışıp durduğunuz şeyler hakkında aranızda ben hüküm vereceğim.\"",
  "56.	\"Küfre sapanlar var ya, işte onlara dünyada ve âhirette şiddetle azap edeceğim. Hiçbir yardımcıları olmayacaktır onların.\"",
  "57.	İman edip hayra ve barışa yönelik işler yapanlara gelince, Allah onlara ödüllerini tam olarak verecektir. Allah zalimleri sevmez.",
  "58.	İşte bu sana ayetlerden ve hikmetlerle dolu Zikir'den okuduğumuzdur.",
  "59.	Allah katında İsa'nın durumu, Âdem'in durumu gibidir. Onu topraktan yarattı, sonra ona \"Ol!\" dedi.Artık o, olur.",
  "60.	Hak, Rabbindendir.O halde, kuşku duyanlardan olma.",
  "61.	Sana ilimden bir nasip geldikten sonra, hak konusunda seninle tartışana de ki: \"Gelin; oğullarımızı ve oğullarınızı, kadınlarımızı ve kadınlarınızı, öz benliklerimizi ve öz benliklerinizi çağıralım, mübâhele edelim de Allah'ın lanetini yalancılar üzerine salalım.\"",
  "62.	İşte, gerçek kıssanın ta kendisi budur. Allah'tan başka ilah yoktur. Ve Allah, elbette Azîz'dir, elbette Hakîm'dir.",
  "63.	Eğer yüz çevirirlerse, hiç kuşkusuz Allah, bozguncuları çok iyi bilmektedir.",
  "64.	De ki: \"Ey Ehlikitap! Sizin ve bizim aramızda aynı olan şu söze gelin: \"Allah'tan başkasına kulluk etmeyelim, O'na hiçbir şeyi ortak koşmayalım. Allah'ın berisinden birbirimizi rabler edinmeyelim!\" Eğer yüz çevirirlerse şöyle söyle: \"Tanık olun, biz müslümanlarız/Allah'a teslim olanlarız!\"",
  "65.	Ey Ehlikitap! İbrahim hakkında neden çekişiyorsunuz? Tevrat da İncil de ondan sonra indirildi. Hâlâ aklınızı işletmeyecek misiniz?",
  "66.	İşte siz böyle insanlarsınız! Hakkında biraz bilginiz olan şeyde çekişmeye girdiniz. Peki, hakkında hiçbir bilginiz olmayan şeyde neden tartışmaya giriyorsunuz? Allah bilir ama siz bilmezsiniz.",
  "67.	İbrahim ne bir Yahudi idi ne de bir Hıristiyan. O, sadece Hanîf bir müslümandı/Allah'a teslim olandı. O müşriklerden değildi.",
  "68.	Şu bir gerçek ki, insanların İbrahim'e gönülce en yakın olanları, elbette ona uyanlar, bu peygamber, bir de iman sahipleridir. Allah, müminlerin Velî'sidir.",
  "69.	Kitap ehlinden bir zümre, sizi bir saptırabilseler diye arzu ettiler. Oysaki onlar, kendilerinden başkasını saptırmazlar. Ama bunu fark etmiyorlar.",
  "70.	Ey Ehlikitap! Gerçeğe tanık olup durduğunuz halde, Allah'ın ayetlerini neden inkâr ediyorsunuz/Allah'ın ayetlerine neden nankörlük ediyorsunuz?!",
  "71.	Ey Ehlikitap! Neden hakkı bâtılla kirletiyorsunuz ve bilip durduğunuz halde gerçeği gizliyorsunuz?",
  "72.	Ehlikitap'tan bir zümre şöyle dedi: \"Şu iman edenlere indirilene günün başlangıcında inanın, günün sonunda karşı çıkın. Belki bu sayede geriye/eskiye dönerler.",
  "73.	Dininize uyandan başkasına inanmayın.\" Söyle onlara: \"Hidâyet, Allah'ın kılavuzlamasıdır.Size verilenin benzeri bir başkasına veriliyor yahut Rabbinizin katında tartışarak size üstün gelecekler diye mi bütün bunlar?\" De ki: \"Lütuf Allah'ın elindedir; onu dilediğine verir. Allah Vâsî'dir, varlığı sürekli genişletir; Alîm'dir, her şeyi en iyi şekilde bilir.\"",
  "74.	Rahmetini dilediğine özgüler. Allah, büyük lütfun sahibidir.",
  "75.	Ehlikitap'tan öylesi vardır ki, ona yüklerle emanet teslim etsen onu sana iade eder. Onlardan öylesi de vardır ki, ona bir dînar emanet etsen, tepesine çökmedikçe onu sana geri vermez. Bunun sebebi şudur: Onlar: \"Ümmîlerin, bizim aleyhimize yol bulmaları mümkün değildir.\" demişlerdir. Onlar, bilip durdukları halde, Allah hakkında yalan söylerler.",
  "76.	İş öyle değil! Kim ahdine vefa eder, takvaya sarılırsa hiç kuşkusuz, Allah takvaya sarılanları sever.",
  "77.	Allah'a verdikleri sözü ve yeminlerini basit bir bedel karşılığı satanlar var ya, işte onlar için âhirette hiçbir nasip yoktur. Allah onlarla konuşmayacaktır, kıyamet günü onlara bakmayacaktır, onları temizleyip arıtmayacaktır. Onlar için korkunç bir azap vardır.",
  "78.	Onlardan bir zümre vardır, aslında Kitap'tan olmayan birşeyi siz Kitap'tan sanasınız diye, dillerini Kitap'la eğip bükerler. O, Allah katında olmadığı halde, \"Bu, Allah katındandır.\" derler. Bilip durdukları halde, Allah hakkında yalan söylerler.",
  "79.	Hiçbir insana yakışmaz ki, Allah kendisine kitap, hüküm-hikmet ve peygamberlik versin de sonra o, insanlara \"Allah'ı bırakıp bana kullar olun\" desin. O ancak şöyle der: \"Öğrettiğiniz şu Kitap'a ve okuyup araştırdıklarınıza dayanarak benliklerini Allah'a adamış kullar/Rabbânîler olun!\"",
  "80.	Ve size melekleri ve peygamberleri rabler edinmenizi de emretmez. Siz, müslümanlar haline geldikten sonra inkârı mı emreder size?",
  "81.	Ve unutma ki Allah, peygamberlerden mîsaklarını almış, şöyle demişti: \"Size Kitap'tan ve hikmetten nasip verdim. Sonra size elinizdekini doğrulayıcı bir resul geldiğinde, ona mutlaka inanacak ve ona muhakkak yardım edeceksiniz. Kabul ettiniz ve ağır yükümü üzerinize aldınız mı?\". \"Kabul ettik.\" dediler. \"O halde tanık olun, sizinle beraber ben de tanıklardanım.\" dedi.",
  "82.	Tüm bunlardan sonra yüz çevirenler, sapıkların ta kendileridir.",
  "83.	Hâlâ Allah'ın dininden gayrısını mı arıyorlar? Oysaki, göklerdeki şuurlular da, yerdekiler de ister istemez O'na teslim olmuşlardır ve yalnız O'na döndürüleceklerdir.",
  "84.	De ki: \"Allah'a, bize indirilene, İbrahim'e, İsmail'e, İshak'a, Yakub'a, torunlarına indirilmiş olana, Mûsa'ya, İsa'ya ve diğer nebilere Rablerinden verilmiş bulunana inandık. Onlardan hiçbirini ötekinden ayırmayız. Biz O'na teslim olanlarız.\"",
  "85.	Kim İslam'dan/Allah'a teslim olmaktan gayrı bir din ararsa artık o, ondan asla kabul edilmeyecektir. Ve o, âhirette hüsrana düşenlerdendir.",
  "86.	İmanlarından, resulün hak olduğuna tanıklık ettikten ve kendilerine ayan-beyan deliller geldikten sonra küfre sapmış bir topluluğa Allah nasıl kılavuzluk eder? Allah, zalimler topluluğuna yol göstermez.",
  "87.	İşte böylelerinin cezası: Allah'ın, meleklerin ve tüm insanların laneti üzerlerine!",
  "88.	O lanet içinde sürekli kalacaklardır. Ne azap hafifletilecektir onlardan ne de yüzlerine bakılacaktır onların.",
  "89.	Ondan sonra tövbe edip hallerini düzeltenler müstesna. Hiç şüphesiz, Allah, çok affedici, çok merhametlidir.",
  "90.	İmanlarından sonra küfre sapmış, sonra da küfürde daha da azıtmış olanların tövbeleri asla kabul edilmeyecektir. Onlar, sapıkların ta kendileridir.",
  "91.	Gerçeği örtüp de küfre sapmış olarak ölenlere gelince, onların her biri kendini kurtarmak için dünya dolusu altın verse de asla kabul edilmeyecektir. Korkunç bir azap vardır onlar için. Hiçbir yardımcıları olmayacaktır.",
  "92.	Sevdiğiniz şeylerden infak etmedikçe hayırda erginliğe/dürüstlüğe asla ulaşamazsınız. İnfak etmekte olduğunuz her şeyi, Allah çok iyi bilmektedir.",
  "93.	Tevrat indirilmeden önce İsrail'in kendi nefsine haram kıldığı şeyler dışında tüm yiyecekler İsrailoğullarına helaldi. Onlara de ki: \"Tevrat'ı ortaya getirin; doğru sözlü iseniz onu okuyun.\"",
  "94.	Artık bundan sonra kim yalan düzüp Allah'a iftira ederse böyleleri zalimlerin ta kendileridir.",
  "95.	De ki: \"Allah, doğrusunu söylemiştir/vaadinde sadıktır. Hadi artık hanîf olarak İbrahim'in milletine uyun! Müşriklerden değildi o.\"",
  "96.	Şu bir gerçek ki, âlemlere bir bereket kaynağı ve yol gösterici halinde insanlar için kurulan ilk ev Mekke'dekidir.",
  "97.	Açık-seçik deliller, İbrahim'in makamı vardır orada. Oraya giren, güvene ermiş olur. Yoluna gücü yetenin o evi ziyaret etmesi, insanlar üzerinde Allah'ın bir hakkıdır. Kim nankörlük ederse hiç kuşkusuz, Allah bütün âlemlere muhtaç olmayacak bir Ganî'dir.",
  "98.	De ki: \"Ey Ehlikitap! Allah, yaptıklarınıza tanıklık ederken, Allah'ın ayetlerini neden inkâr ediyorsunuz?\"",
  "99.	Şunu da söyle: \"Ey Ehlikitap! Neden iman edenleri Allah yolundan alıkoyuyorsunuz? Gözünüzle gördüğünüz halde, Allah yolunu neden çarpıtmak istiyorsunuz? Allah, yaptıklarınızdan habersiz değildir.\"",
  "100.	Ey iman edenler! Kendilerine kitap verilenlerden bir zümreye boyun eğerseniz sizi, imanınızdan sonra kâfirler haline getirirler.",
  "101.	Allah'ın ayetleri size okunuyor, Resulü de aranızda; peki, nasıl küfre sapıyorsunuz? Kim Allah'a sarılırsa dosdoğru yola iletilmiştir o...",
  "102.	Ey iman edenler! Allah'tan, kendisinden korkmaya yaraşır biçimde korkun. Müslümanlar olmanın/Allah'a teslim olmanın dışında bir hal üzere sakın can vermeyin.",
  "103.	Hep birlikte Allah'ın ipine yapışın, fırkalara bölünüp parçalanmayın; Allah'ın üzerinizdeki nimetini hatırlayın. Birbirinizin düşmanı idiniz, Allah kalplerinizi uzlaştırıp kaynaştırdı da O'nun nimeti sayesinde kardeşler haline geldiniz. Ateşten bir çukurun kenarında idiniz; sizi oradan kurtardı. Allah size ayetlerini bu şekilde açıklıyor ki, doğruya ve güzele yol bulasınız.",
  "104.	İçinizden hayra çağıran, doğruluk ve güzelliği belirlenene özendiren, kötülük ve çirkinliği belirlenenden sakındıran bir topluluk olsun. Kurtuluş ve zafere erenler işte onlardır.",
  "105.	Kendilerine açık-seçik kanıtlar geldikten sonra, çekişmeye girip fırkalar halinde parçalananlar gibi olmayın. Böyle olanlar için çok büyük bir azap vardır.",
  "106.	Gün gelir bazı yüzler ağarır, bazı yüzler kararır. Yüzleri kararanlara şöyle denir: \"İmanınızdan sonra küfre mi düştünüz? Hadi, saptığınız küfür yüzünden tadın azabı!\"",
  "107.	Yüzleri ağaranlara gelince, onlar, Allah'ın rahmeti içindedirler. Sürekli ondadır onlar.",
  "108.	Bunlar sana Allah'ın ayetleri. Hak olarak okuyoruz sana onları. Allah, âlemlere zulüm istemiyor.",
  "109.	Göklerde ne var, yerde ne varsa hepsi Allah'ındır. İş ve oluşlar Allah'a döndürülür.",
  "110.	Siz, insanlar için çıkarılmış en hayırlı ümmetsiniz: İyilik ve güzelliği belirlenmiş olana özendirirsiniz, kötülük ve çirkinliği belirlenmiş olandan sakındırırsınız, Allah'a iman edersiniz. Ehlikitap da iman etseydi, kendileri için, elbette hayırlı olurdu. İçlerinde müminler vardır ama onların çoğu sapıkların ta kendileridir.",
  "111.	Biraz eziyet dışında size asla zarar veremezler. Sizinle savaşırlarsa size sırtlarını dönerler. Sonra onlara yardım da edilmez.",
  "112.	Allah'tan bir ipe ve insanlardan bir ipe tutunmaları dışında, nerede bulunsalar üzerlerine zillet damgası vurulur. Allah'ın hışmına uğramışlardır. Üzerlerine miskinlik damgası vurulmuştur. Bu böyledir. Çünkü onlar, Allah'ın ayetlerine küfrediyor, haksız yere peygamberleri öldürüyorlardı; isyan etmişlerdi, zulüm ve azgınlık sergiliyorlardı.",
  "113.	Ama hepsi bir değildir. Ehlikitap içinden Allah için baş kaldıran/Allah huzurunda el bağlayan/hak ve adaleti ayakta tutan/kalkınıp yükselen bir zümre de vardır; gece saatlerinde secdelere kapanmış olarak Allah'ın ayetlerini okurlar.",
  "114.	Allah'a ve âhiret gününe inanırlar, iyilik ve güzelliği belirlenmiş olana özendirirler, kötülük ve çirkinliği belirlenmiş olandan sakındırırlar. Hayır işlerde yarışırcasına koşarlar. İşte bunlar hayra ve barışa yönelik hizmet üretenlerdendir.",
  "115.	Yapmakta oldukları/yapacakları hiçbir hayır, nankörlükle karşılanmayacak/karşılıksız bırakılmayacaktır. Allah, takva sahiplerini çok iyi bilmektedir.",
  "116.	Küfre sapanlara gelince, onların malları da çocukları da kendilerine Allah'a karşı bir yarar asla sağlamayacaktır. Ateşin dostlarıdır onlar. Sürekli kalacaklardır onun içinde.",
  "117.	Bu dünya hayatında harcamakta olduklarının durumu, bir rüzgâr örneğine benzer: Onda kavurucu bir soğuk vardır. Öz benliklerine zulmetmiş bir toplululuğun ekinine değmiş de onu mahvetmiştir. Allah onlara zulmetmedi, onlar kendilerine zulmediyorlardı.",
  "118.	Ey iman sahipleri! Kendi dışınızdakilerden/seviyenizin altındakilerden bir kimseyi sırdaş edinmeyin.Sizi sarpa sardırıp perişan etmekten çekinmezler. Size sıkıntı verecek şeyi pek severler. Ağızlarından nefret ve öfke taşmaktadır. Göğüslerinin saklamakta olduğu ise daha büyüktür. Eğer aklınızı işletirseniz Allah size ayetlerini açık-seçik göstermiştir.",
  "119.	Siz öyle kişilersiniz ki, onlar sizi sevmedikleri halde siz onları seversiniz. Ve Kitap'ın tümüne inanırsınız. Onlar ise sizinle karşılaştıklarında \"İnandık!\" derler; başbaşa kaldıklarında ise size öfkelerinden parmak uçlarını ısırırlar. De ki onlara: \"Öfkenizle geberin!\" Allah, göğüslerin içindekini çok iyi bilmektedir.",
  "120.	Size bir iyilik dokunsa bu onları rahatsız eder. Size bir kötülük dokunsa bununla sevinir, ferahlarlar. Eğer sabreder, sakınır/korunursanız onların tuzakları size hiçbir şekilde zarar veremez. Allah Muhît'tir, yapmakta olduklarını çepeçevre kuşatmıştır.",
  "121.	Hani, sen ailenden erkenden ayrılmıştın da müminleri savaş için tutulması gereken noktalara yerleştiriyordun. Allah her şeyi çok iyi duyar, çok iyi bilir.",
  "122.	Sizden iki takım, korku ile bozulmak üzereydi. Halbuki Allah onların Velî'siydi. Müminler yalnız Allah'a güvenip dayansınlar.",
  "123.	Yemin olsun ki, ezik-boynu bükük olduğunuz bir sırada Allah size Bedir'de de yardım etmişti.O halde Allah'tan korkun ki, şükredebilesiniz.",
  "124.	O sırada sen, müminlere şöyle diyordun: \"Rabbinizin, indirilmiş üçbin melekle destek vermesi, size yetmiyor mu?\"",
  "125.	İş, sanıldığı gibi değildir. Onlar, hemen şu anda üstünüze gelseler bile, eğer siz sabreder ve korunursanız, Rabbiniz sizi, üzerlerine nişan vurulmuş beş bin melekle destekler.",
  "126.	Allah, bunu, size bir müjde olması ve onunla kalplerinizi yatıştırması dışında hiçbir şey yapmamıştır.Yardım, Azîz ve Hakîm olan Allah katından başka hiçbir yerden gelmez.",
  "127.	Allah bunu yaptı ki, küfre sapanlardan bir kısmını bölüp ayırsın veya onları zelîl etsin de yıkık ve ürkek bir halde dönüp gitsinler.",
  "128.	İş ve hüküm konusunda sana düşen bir şey yoktur.Allah ya tövbelerini kabul ederek onları bağışlar yahut da zalim oldukları için onlara azap eder.",
  "129.	Göklerde ne var, yerde ne varsa Allah'ındır. Dilediğini/dileyeni affeder; dilediğine/dileyene azap eder. Allah çok affedici, çok merhametlidir.",
  "130.	Ey iman sahipleri! Ribayı öyle kat kat katlayarak yemeyin. Allah'tan korkun ki kurtuluşa erebilesiniz.",
  "131.	Kâfirler için hazırlanmış ateşten korkun.",
  "132.	Allah'a ve resule itaat edin ki, merhamet görebilesiniz.",
  "133.	Rabbinizden bir bağışlanmaya ve eni göklerle yer kadar olan cennete doğru yarışır gibi koşuşun. O, takva sahipleri için hazırlanmıştır.",
  "134.	Onlar bollukta ve darlıkta infak ederler. Öfkelerini yutanlardır onlar, insanları affedenlerdir. Allah, güzel düşünüp güzel davrananları sever.",
  "135.	Onlar, çirkin bir iş yaptıklarında yahut öz benliklerine zulmettiklerinde, Allah'ı hatırlarlar da günahları için af dilerler. Günahları Allah'tan başka kim affeder ki? Ve onlar yaptıklarında bile bile ısrar etmezler.",
  "136.	İşte bunların ödülleri Rablerinden bir bağışlanma ve altlarından ırmaklar akan cennetler olacaktır. Sürekli kalacaklardır orada. İş yapıp değer üretenlerin ücreti ne güzeldir!",
  "137.	Sizden önce de yollar-yöntemler gelip geçmiştir. O halde yeryüzünde dolaşın da yalanlayanların sonu nice olmuştur görün.",
  "138.	Bu, insanlara bir açıklama, korunup sakınanlara da bir öğüt ve kılavuzdur.",
  "139.	Gevşemeyin, tasalanmayın. Eğer inanıyorsanız üstün olan sizsiniz.",
  "140.	Size bir yara değiyorsa, o topluma da benzeri bir yara mutlaka değmiştir. Bak işte günler! Biz onları insanlar arasında dolandırır dururuz. Allah bu sayede iman edenleri bilecek, sizden tanıklar/şehitler edinecektir. Allah zulme sapanları sevmez.",
  "141.	Tüm bunlar, Allah iman edenleri iyice seçip arındırsın ve küfre sapanları mahvetsin diyedir.",
  "142.	Yoksa siz, Allah içinizden uğraşıp didinenleri seçmeden, sabredenleri seçmeden cennete gireceğinizi mi sandınız?",
  "143.	Yemin olsun ki siz, onunla karşılaşmadan önce ölümü arzuluyordunuz. İşte gördünüz onu ve bakıp duruyorsunuz.",
  "144.	Muhammed bir resulden başkası değildir. Ondan önce de resuller gelip geçmiştir. Şimdi o ölse yahut öldürülse ökçeleriniz üzerine gerisin geri mi döneceksiniz! İki ökçesi üzerine geri dönen, Allah'a hiçbir şekilde zarar veremez. Allah, şükredenleri ödüllendirecektir.",
  "145.	Allah'ın izni olmadıkça hiçbir kişi ölmez. Vakti belirlenmiş bir yazıdır o. Dünya çıkarını gözetene ondan veririz; âhiret yararını gözetene de ondan veririz. Şükredenleri ödüllendireceğiz biz.",
  "146.	Nice peygamber, beraberinde kendisini Rabb'e adayan birçok kişi bulunduğu halde savaşmıştır. Onlar, Allah yolunda kendilerine gelip çatan zorluklar yüzünden gevşememiş, zayıflık göstermemiş, susup pusmamışlardır. Allah sabredenleri sever.",
  "147.	Sözleri yalnız şu olmuştur: \"Ey Rabbimiz! Bağışla bizim günahlarımızı, affet işlerimizdeki taşkınlığımızı, sağlam bastır ayaklarımızı ve yardım et bize küfre sapan topluma karşı!\"",
  "148.	Allah da onlara, hem dünya nimetini verdi hem de âhiret sevabının en güzelini. Allah, güzel düşünüp güzellik sergileyenleri sever.",
  "149.	Ey iman edenler! Eğer küfre sapanlara boyun eğerseniz sizi ökçeleriniz üstüne gerisin geri çevirirler de hüsrana uğrayanlar haline gelirsiniz.",
  "150.	Hayır, hayır! Sizin Mevlâ'nız Allah'tır. Ve O, yardımcıların en hayırlısıdır.",
  "151.	Allah'ın, kendileri hakkında hiçbir delil indirmediği şeyleri Allah'a ortak koştukları için, küfre sapanların kalplerine korku salacağız. Barınakları ateştir onların. Ne kötüdür o zalimlerin varacakları yer!",
  "152.	Yemin olsun ki, siz onları Allah'ın izniyle öldürmekteyken, Allah size vaadini doğrulamıştı. Nihayet,siz korkuya kapıldınız, yapılacak iş hususunda çekiştiniz. Ve Allah, sevdiğiniz şeyi size gösterdikten sonra isyan ettiniz. İçinizden bir kısmı dünyayı istiyordu, bir kısmınız ise âhireti istiyordu. Sonra sizi imtihan etmek için onlardan uzaklaştırdı. Yemin olsun, sizi affetmişti. Allah, müminlere karşı lütuf sahibidir.",
  "153.	Siz şaşkınlıkla sağa-sola kaçıyor, hiç kimseye dönüp bakmıyordunuz. Resul ise arkanızdan sizi çağırıyordu. Böylece Allah size keder üstüne keder verdi ki, elinizden uçup gidene de size isabet edene de üzülmeyesiniz. Allah, yapmakta olduklarınızdan haberdardır.",
  "154.	Sonra bu kederin ardından üzerinize, içinizden bir grubu sarıp kuşatan, güven verici bir uyku indirdi. Bir grup da -gerçekten onlar kendi canlarının derdine düşmüştü- Allah hakkında gerçek dışı sanılara, cahiliye düşüncelerine kapılıyordu. \"Şu işten bize bir şey var mı?\" diyorlardı. De ki: \"Emir/iş ve oluş tümüyle Allah'ındır.\" Öz benliklerinde, sana açıklamaz oldukları şeyler saklıyorlar. Diyorlar ki: \"Bu işten bizim lehimize bir şey olsaydı, şuracıkta öldürülmezdik.\" Söyle onlara: \"Evlerinizde kalsaydınız bile, üzerlerine ölüm yazılmış olanlar, uzanacakları yerleri muhakkak boylayacaklardı.\" Bu, Allah, göğüslerinizdekini denesin, kalplerinizdekini ortaya çıkarsın diyedir. Allah, göğüslerin özünü çok iyi bilir.",
  "155.	İki topluluğun karşılaştığı gün geri dönüp gidenleriniz var ya, yaptıkları bazı işler yüzünden şeytan onların ayağını kaydırmak istemişti.Yemin olsun, Allah onları yine de affetti. Allah Gafûr'dur, Halîm'dir.",
  "156.	Ey iman sahipleri! Yeryüzünde dolaşan yahut gazaya çıkan kardeşleri için şöyle diyen inkârcılar gibi olmayın: \"Yanımızda olsaydılar ölmezlerdi, öldürülmezlerdi.\" Allah bunu onların kalplerinde bir özlem yapacaktır. Allah, diriltir de öldürür de. Allah, yapıp ettiklerinizi en iyi şekilde görmektedir.",
  "157.	Allah yolunda öldürülür yahut ölürseniz, Allah'tan bir bağışlanma ve bir merhamet/bir sevgi onların derleyip topladıklarından çok daha iyidir.",
  "158.	Ölür yahut öldürülürseniz elbette ki Allah'a götürüleceksiniz.",
  "159.	Allah'tan bir merhamet/bir sevgi sayesindedir ki, sen onlara yumuşak davrandın. Eğer kaba-saba, katı yürekli olsaydın senin çevrenden kesinlikle dağılır giderlerdi. O halde bağışla onları, af dile onlar için; iş ve yönetim konusunda da onlarla şûraya git. Bir kez azmettin mi de artık Allah'a güvenip dayan!Allah, tevekkül edenleri sever.",
  "160.	Allah size yardım ederse hiç kimse size galip gelemez. Eğer sizi yüzüstü bırakırsa O'ndan başka size kim yardım edebilir? Artık müminler yalnız Allah'a güvenip dayansınlar.",
  "161.	Bir peygamberin emanete hıyanet etmesi/kamu malından aşırması olacak şey değildir. Her kim hıyanet eder, kamu malından bir şey aşırırsa, aşırdığını kıyamet günü yüklenip getirir. Sonra her benliğe; kazandığı tam olarak ödenir. Hiç birine zulmedilmez.",
  "162.	Allah'ın hoşnutluğunu izleyen kişi, Allah'ın gazabına uğrayan ve barınağı cehennem olan kişiyle aynı mıdır? Ne kötü varış yeridir o!",
  "163.	Onlar, Allah katında derece derecedirler. Allah, yapmakta olduklarını iyice görmektedir.",
  "164.	Yemin olsun ki, Allah müminlere lütufta bulunup onları minnettar bırakmıştır: Kendi içlerinde onlara öyle bir resul gönderdi ki, onlara Allah'ın ayetlerini okuyor, onları temizleyip arındırıyor, onlara Kitap'ı ve hikmeti öğretiyor. Oysaki onlar, bundan önce açık bir sapıklığın tam içindeydiler.",
  "165.	Size, başkalarına iki katını dokundurduğumuz bir musibet dokununca: \"Bu da nereden!\" mi dediniz? De ki: \"O, sizin öz benliklerinizdendir.\" Allah, her şeye Kadîr'dir.",
  "166.	İki topluluğun karşılaştığı gün sizin başınıza gelen, Allah'ın izniyledir ve Allah, müminleri bilsin diyedir.",
  "167.	Ve ikiyüzlülük yapan münafıkları bilsin diye. Onlara, \"Hadi gelin, Allah yolunda çarpışın yahut savunma yapın!\" dendiğinde: \"Savaştan haberimiz olsaydı sizi elbette izlerdik.\" dediler. O gün onlar, imandan çok küfre yakın idiler. Kalplerinde olmayanı ağızlarıyla söylüyorlar. Allah, onların gizlemekte oldukları şeyi çok iyi bilmektedir.",
  "168.	Yerlerinde oturup da kardeşleri için, \"Bizi dinlemiş olsalardı öldürülmeyeceklerdi.\" diyenlere şöyle söyle: \"Eğer doğru sözlüler iseniz, kendi benliklerinizden uzaklaştırın ölümü!\"",
  "169.	Allah yolunda öldürülmüş olanları ölüler sanma sakın. Hayır! Onlar diridirler. Rablerinin katında rızıklandırılıyorlar.",
  "170.	Allah'ın, lütfundan kendilerine verdiğiyle sevinçlidirler. Ve arkada kalıp kendilerine katılmamış olanlara şunu müjdeliyorlar: Onlar için korku yoktur; tasalanmayacaklardır onlar.",
  "171.	Allah'tan bir nimeti, bir lütfu ve Allah'ın müminlerin ödülünü vermezlik etmeyeceğini de müjdelerler.",
  "172.	O müminler ki, kendilerine yara isabet ettikten sonra bile Allah'ın ve resulün çağrısına cevap verdiler. Onlar içinden, güzel işler yapıp takvaya sarılanlara büyük bir ödül vardır.",
  "173.	O müminler ki, insanlar kendilerine, \"Halk size karşı bir araya gelmiş, korkun onlardan!\" dediklerinde, bu onların imanını artırdı da şöyle söylediler: \"Allah bize yeter. Ne güzel Vekîl'dir O!\"",
  "174.	Böyle olduğu içindir ki, Allah'tan bir nimet ve lütufla geri döndüler, hiçbir kötülük dokunmamıştı onlara. Allah'ın rızasını izlediler. Allah çok büyük bir lütfun sahibidir.",
  "175.	İşte size şeytan. O yalnız kendi dostlarını korkutur. Eğer inananlarsanız onlardan korkmayın, benden korkun.",
  "176.	Küfür içinde koşuşanlar sana üzüntü vermesin. Şu bir gerçek ki, onlar Allah'a hiçbir şekilde zarar veremezler. Allah, onlara âhirette bir nasip vermemeyi istemektedir. Onlar için çok büyük bir azap öngörülmüştür.",
  "177.	İman karşılığında küfrü satın alanlar, Allah'a herhangi bir biçimde asla zarar veremezler. Korkunç bir azap vardır onlar için.",
  "178.	Küfre sapanlar, onlara süre tanımamızın kendileri için hayırlı olduğunu asla düşünmesinler. Onlara, biraz daha günah işlesinler diye süre veriyoruz. Yere geçirecek bir azap var onlar için.",
  "179.	Allah, müminleri şu üzerinde bulunduğunuz halde bırakmayacaktır. Sonuçta pisi temizden ayıracaktır. Allah sizi gaybı bilir duruma da getirmeyecektir. Şu var ki Allah, resullerinden dilediğini seçer. O halde Allah'a ve resullerine inanın. Eğer inanır, korunursanız sizin için büyük bir ödül vardır.",
  "180.	Allah'ın, lütfundan kendilerine verdiği şeyde cimrilik edenler, bunun kendileri için hayırlı olduğunu sanmasınlar. Tam aksine bu onlar için bir şerdir. O cimrilik konusu yaptıkları şey, kıyamet günü bir tasma gibi boyunlarına dolandırılacaktır. Göklerin ve yerin mirası Allah'ındır. Allah, yapmakta olduklarınızdan haberdardır.",
  "181.	Yemin olsun ki, Allah, \"Allah yoksuldur, bizler zenginleriz!\" diyenlerin sözünü işitti. Dediklerini de yazacağız, haksız yere peygamberleri öldürmelerini de. Ve şöyle diyeceğiz: \"Tadın, yakıp pişiren azabı!\"",
  "182.	Bu, kendi, ellerinizin üretip önden gönderdiği yüzündendir. Allah, kullara asla zulmedici değildir.",
  "183.	Onlar şöyle demişlerdi: \"Allah bize ant verdi, kendisi bize ateşin yiyeceği bir kurban getirmedikçe hiçbir resule inanmayacağız.\" Söyle onlara: \"Size benden önce o dediğinizle birlikte açık deliller getiren resuller gelmişti. Peki, madem doğru sözlülerdiniz neden onları katlettiniz?\"",
  "184.	Seni yalanladılarsa, senden önce de resuller yalanlandı. Açık-seçik deliller, kutsal sayfalar ve aydınlatıcı kitabı getirmişlerdi onlar.",
  "185.	Her benlik ölümü tadacaktır. Hak ettiğiniz karşılıklar size, kıyamet günü, eksiksiz bir biçimde mutlaka verilecektir. Ateşten uzaklaştırılıp cennete sokulan kesinlikle kurtulmuş olacaktır. İğreti-sefil hayat aldatıcı bir yararlanmadan başka şey değildir.",
  "186.	Yemin olsun ki, mallarınızda da canlarınızda da imtihan edileceksiniz. Ve yemin olsun ki, sizden önce kendilerine kitap verilenlerden de şirke batanlardan da incitici çok şey dinleyeceksiniz. Sabreder,sakınıp korunursanız işte bu, iş ve oluşların en zorlularındandır.",
  "187.	Allah, kendilerine kitap verilenlerden şu yolda mîsak almıştı: \"Onu insanlara mutlaka açık-seçik bildireceksiniz, onu saklamayacaksınız.\" Ama onlar Kitap'ı sırtlarının gerisine attılar, basit bir ücret karşılığı onu sattılar. Ne kötü şey satın alıyorlar!",
  "188.	O ettikleriyle zevklenen, yapmadıkları şeylerle övünmeyi seven kişileri bir şey sanma. Artık, onları azaptan kurtulmuş da sanma. Korkunç bir azap vardır onlar için.",
  "189.	Göklerin de yerin de mülkü/yönetimi Allah'ındır. Allah Kadîr'dir, her şeye gücü yeter.",
  "190.	Şu bir gerçek ki, göklerin ve yerin yaratılışında, geceyle gündüzün birbiri ardınca gelişinde, akıllarını/gönüllerini işletenler için çok ibretler vardır.",
  "191.	Onlar o kişilerdir ki, ayakta, otururken, yan yatarken hep Allah'ı zikrederler; göklerin ve yerin yaratılışı hakkında derin derin düşünürler: \"Ey Rabbimiz! Sen bunu boşuna yaratmadın. Şanın yücedir senin!Ateş azabından koru bizi!\"",
  "192.	\"Ey Rabbimiz! Sen birini ateşe soktun mu onu tam rezil etmişsindir. Zalimlerin, yardımcıları olmayacaktır.\"",
  "193.	\"Ey Rabbimiz! Bir çağırıcının, 'Rabbinize inanın!' diye imana çağırdığını işittik ve iman ettik. Ey Rabbimiz! Günahlarımızı bağışla bizim. Kötülüklerimizin üstünü ört ve bize iyilerle birlikte ölmek nasip et.\"",
  "194.	\"Ey Rabbimiz! Resullerin aracılığıyla bize vaat etmiş olduğunu da bize ver; kıyamet günü bizi rezil etme!Sen, vaadine asla ters düşmezsin.\"",
  "195.	Rableri onlara cevap verdi: \"Ben sizden, erkek-kadın hiçbir çalışanın ürettiğini boşa çıkarmayacağım. Hep birbirinizdensiniz. Göç edenler, yurtlarından çıkarılanlar, yolumda işkenceye uğratılanlar, çarpışıp da öldürülenler var ya, onların kötülüklerini yemin olsun örteceğim. Ve yemin olsun ki onları, Allah katından bir karşılık olarak, altlarından ırmaklar akan cennetlere koyacağım.\" Allah katındandır karşılıkların en güzeli.",
  "196.	Küfre sapanların öyle belde belde dolaşmaları seni sakın aldatmasın.",
  "197.	Azıcık bir nimetlenmedir o. Sonra onların varacağı yer cehennem olacaktır. Ne kötü yataktır o!",
  "198.	Ama Rablerinden sakınanlar için altlarından ırmaklar akan cennetler var. Allah katından bir konukseverlikle sürekli kalıcıdırlar orada. Allah katındaki ödüller iyiler için daha hayırlıdır.",
  "199.	Ehlikitap'tan öyleleri var ki, Allah'a, size indirilene ve kendilerine indirilene inanırlar. Allah karşısında ürperirler; Allah'ın ayetlerini basit bir ücret karşılığı satmazlar. İşte bunlar için Rableri katında kendilerine özgü ödüller vardır. Allah, hesabı, çabucak görüverir.",
  "200.	Ey iman sahipleri! Sabredin, sabır yarışı yapın, nöbet tutarak savaşa hazırlıklı bulunun ve Allah'tan sakının ki, kurtuluşa erebilesiniz."
];
