final List<String> isra = [
  "1.	Bütün varlıkların tespihi o kudretdir ki, ayetlerimizden bazılarını kendisine gösterelim/kendisini ayetlerimizden bir parça olarak gösterelim diye kulunu, gecenin birinde Mescit-i Haram'dan, çevresini bereketlendirdiğimiz Mescid-i Aksa'ya/o en uzak secdegâha yürütmüştür. Hiç kuşkusuz, O'dur Semî' ve Basîr.",
  "2.	Mûsa'ya Kitap'ı verdik ve onu, \"Benden başka bir vekil tutmayın!\" buyruğuyla Beniisrail'e bir kılavuz kıldık.",
  "3.	Ey Nûh ile beraber taşıdığımız kişilerin soyu! Gerçek şu ki, Nûh çok şükreden bir kuldu.",
  "4.	Biz, Beniisrail'e Kitap'ta şu yolda bir yargıda bulunduk: Siz yeryüzünde muhakkak iki kez bozgun vücuda getireceksiniz ve muhakkak büyük bir kibirle böbürleneceksiniz.",
  "5.	Nihayet, o ikiden birincinin vadesi geldiğinde, üzerinize aşılmaz bir güce sahip kullarımızı gönderdik de onlar, barınakların aralarına girip araştırdılar. Ve bu, yerine getirilmiş bir vaat idi.",
  "6.	Sonra onlar üzerinde size tekrar egemenlik verdik, mallar ve oğullarla sizi güçlendirdik ve sizi toplum olarak çoğalttık.",
  "7.	Eğer güzel davranırsanız, kendi benlikleriniz için güzellik sergilemiş olursunuz. Ve eğer kötülük yaparsanız o da benlikleriniz aleyhine olur. Bu sırada, yüzlerinizi çirkinleştirsinler, ilk kez girdikleri gibi mabede girsinler ve egemenlik altına aldıklarını yerle bir etsinler diye ikinci vaat geldi.",
  "8.	Rabbiniz size belki rahmet eder. Ve eğer yine eski duruma dönerseniz, biz de döneriz. Ve biz, cehennemi, küfre batanlar için çepeçevre kuşatan bir zından yapmışızdır.",
  "9.	Şüpheniz olmasın ki bu Kur'an en kalıcı, en doğru olana kılavuzlar ve müminlere şu yolda müjde verir: Barışa/hayra yönelik işler yapanlar için büyük bir ödül vardır.",
  "10.	Âhirete inanmayanlar var ya, onlar için biz korkunç bir azap hazırlamışızdır.",
  "11.	İnsan, hayra davet eder gibi şerri çağırıyor/insan, hayra duasıyla şerri davet ediyor. İnsan çok acelecidir.",
  "12.	Biz, geceyi ve gündüzü iki ayet yaptık; sonra gecenin ayetini silip gündüzün ayetini gösterici yaptık ki, Rabbinizden bir lütuf isteyesiniz, yılların sayısını ve hesabı bilesiniz. Biz her şeyi ayrıntılı bir biçimde açıkladık.",
  "13.	Her insanın uğursuzluk kuşunu onun boynuna takmışızdır. Kıyamet günü kendisine, önünde açılmış olarak bulacağı bir kitap çıkaracağız:",
  "14.	\"Oku kitabını! Bugün sana hesap sorucu olarak öz benliğin yeter.\"",
  "15.	Kim yola gelirse kendisi için yola gelmiş olur. Sapıtan da kendi aleyhine sapıtmış olur. Hiçbir günahkâr, bir başka günahkârın yükünü taşımaz. Ve biz, bir resul göndermedikçe azap edici değiliz.",
  "16.	Biz bir ülkeyi/medeniyeti mahvetmek istediğimizde, onun servet ve nimetle şımarmış elebaşlarına emirler yöneltiriz/onları yöneticiler yaparız da onlar, orada bozuk gidişler sergilerler. Böylece o ülke/medeniyet aleyhine hüküm hak olur; biz de onun altını üstüne getiririz.",
  "17.	Nûh'tan sonra da nice kuşakları helak ettik. Kullarının günahlarını haber alıcı ve görücü olarak Rabbin yeter.",
  "18.	Peşin isteyene dünyada peşin veririz: Dilediğimize dilediğimiz kadar. Sonra da ona cehennemi veririz; yaslanır ona, kınanmış ve kovulmuş olarak.",
  "19.	Kim de âhireti ister ve inanmış olarak ona yaraşır bir gayretle çalışırsa, böylelerinin gayretleri teşekkürle karşılanır.",
  "20.	Rabbinin lütfundan nimetlerle hepsine uzanırız: Onlara da bunlara da. Rabbinin lütfu, kimse tarafından engellenemez/kısıtlanamaz.",
  "21.	Bak nasıl, kimini kimine üstün kıldık! Ama âhiret, dereceler bakımından elbette daha büyük, lütuflandırma bakımından daha yücedir.",
  "22.	Allah'ın yanına başka bir ilah koyma ki, yapayalnız ve horlanmış olarak oturup kalmayasın!",
  "23.	Rabbin şöyle hükmetti: O'ndan başkasına kulluk/ibadet etmeyin, anaya-babaya çok güzel davranın: Onlardan birisi yahut her ikisi senin yanında ihtiyarlık çağına gelirse sakın onlara \"Öf!\" bile deme; onları azarlama, onlara tatlı-iltifatlı söz söyle.",
  "24.	Rahmetten yerlere eğilme kanadını onlar için indir ve de ki: \"Rabbim, merhametli davran onlara, tıpkı küçüklüğümde beni koruyup büyüttükleri gibi.\"",
  "25.	Benliklerinizin içindekini Rabbiniz daha iyi bilir. Eğer siz barışsever/iyi kişiler olursanız O, tövbeye sarılanları affeder.",
  "26.	Akrabaya hakkını ver! Çaresize, yolda kalana da. Fakat saçıp savurma!",
  "27.	Çünkü saçıp savuranlar şeytanların kardeşleri olurlar. Ve şeytan, kendi Rabbine nankörlük etmiştir.",
  "28.	Eğer onlardan, Rabbinden ümit ettiğin bir rahmeti bekleme yüzünden yüz çevirecek olursan, o zaman onlara yumuşak/tatlı bir söz söyle.",
  "29.	Elini bağlayıp boynuna asma. Ama onu büsbütün de salıverme. Sonra kınanır, hasret içinde bir köşede büzülür kalırsın.",
  "30.	Hiç kuşkusuz Rabbin, dilediğine rızkı açar da kısar da. O, kullarını görüyor, onlardan haber alıyor.",
  "31.	Yoksulluk korkusuyla çocuklarınızı öldürmeyin. Onları da sizi de biz rızıklandırıyoruz. Kuşkusuz, onları öldürmek büyük bir günahtır.",
  "32.	Zinaya yaklaşmayın. Çünkü o iğrenç bir iştir; yol olarak da çok kötüdür.",
  "33.	Allah'ın saygıya layık kıldığı cana haklı bir sebep yokken kıymayın. Kim haksızlıkla öldürülürse, onun velisine yetki/söz hakkı vermişizdir. Ama o da öldürmede sınır tanımazlık etmesin. Çünkü kendisine yardım edilmiştir.",
  "34.	Yetimin malına yaklaşmayın. Ancak rüştüne erişinceye kadar, güzel bir yolla ilgilenebilirsiniz. Ahdinize vefalı olun çünkü verilen söz sorumluluk gerektirir.",
  "35.	Ölçtüğünüz zaman tam ve dürüst ölçün. Hilesiz teraziyle tartın. Bu, hem hayırlı hem de sonuç bakımından güzeldir.",
  "36.	Hakkında bilgin olmayan şeyin ardına düşme! Çünkü kulak, göz ve gönlün hepsi bundan sorumlu tutulacaktır.",
  "37.	Yeryüzünde kasılıp kabararak yürüme! Çünkü sen, yeri asla yırtamazsın, uzunlukça da dağlara ulaşamazsın.",
  "38.	Bütün bu sayılanların kötü olanları, Rabbin katında çirkin görülmüştür.",
  "39.	Bunlar, Rabbinin sana, hikmetten vahyetmiş olduklarıdır. Allah'ın yanına başka tanrı koyma ki, kınanmış ve kovulmuş bir halde cehenneme atılmayasın.",
  "40.	Rabbiniz, oğulları seçip size özgüledi de kendisi meleklerden kızlar mı edindi? Gerçekten siz çok dehşet verici bir söz söylüyorsunuz!",
  "41.	Biz, gerçeği, Kur'an'da türlü biçimlerde ifade ettik ki, düşünüp anlayabilsinler. Fakat bu onların sadece kaçışlarını artırıyor.",
  "42.	De ki: \"Eğer onların dediği gibi Allah'la beraber ilahlar olsaydı, o zaman onlar arşın sahibine varmak için elbette bir yol ararlardı.\"",
  "43.	O hep tespih edilen, onların söylediklerinden çok uzak ve çok yüksek; hem de ölçüye sığmayacak kadar yüksek...",
  "44.	Yedi gök, yerküre ve bunların içindekiler O'nu tespih ederler. Hiçbir şey yoktur ki, O'nu överek tespih etmesin; fakat siz onların tespihlerini fark edemezsiniz. O Halîm'dir, Gafûr'dur.",
  "45.	Kur'an okuduğunda, seninle, âhirete inanmayanlar arasına gizli bir perde çekeriz.",
  "46.	Kalpleri üzerine, onu anlamamaları için kabuklar geçiririz, kulaklarına da bir ağırlık koyarız. Rabbini yalnız Kur'an'da andığın zaman/Kur'an'da yalnız O'nu andığın zaman, nefretle geriye dönüp kaçarlar.",
  "47.	Onların seni dinlerken, neye kulak verdiklerini biz daha iyi biliriz. Aralarında fısıldaşırlarken de şöyle konuşur o zalimler: \"Büyülenmiş bir adamdan başkasının ardı sıra gitmiyorsunuz!\"",
  "48.	Bak nasıl örnekler verdiler sana, nasıl sapıttılar. Artık hiçbir yola varamazlar.",
  "49.	Dediler ki: \"Biz, bir yığın kemik olduğumuz, un-ufak hale geldiğimiz zaman mı, gerçekten biz o zaman mı yeni bir yaratılışla diriltileceğiz.\"",
  "50.	De ki: \"İster taş olun ister demir!\"",
  "51.	\"İsterseniz gönlünüzde büyüyen herhangi bir yaratık olun.\" Diyecekler ki: \"Peki bizi yeniden kim yaratacak?\" De ki: \"Sizi ilk kez yaratan kimse, o!\" Bunun üzerine başlarını sana doğru alaylı bir biçimde sallayarak şöyle konuşacaklar: \"Ne zaman o?\" De ki: \"Çok yakın olabilir!\"",
  "52.	Sizi çağıracağı gün, onu hamt ederek çağrısına derhal uyacaksınız. Ve sadece az bir süre kaldığınızı düşüneceksiniz.",
  "53.	Kullarıma de ki: En güzel olan neyse onu söylesinler. Çünkü şeytan, aralarına yamukluk sokar. Şeytan, insan için apaçık bir düşmandır.",
  "54.	Rabbiniz sizi daha iyi bilir. Dilerse size rahmet eder, dilerse size azap eder. Biz seni onlar üzerine vekil göndermedik.",
  "55.	Rabbin, göklerdeki ve yerdeki kimseleri de daha iyi bilir. Yemin olsun, biz, peygamberlerin bir kısmını bir kısmına üstün kılmışızdır. Davûd'a da Zebur'u verdik.",
  "56.	De ki: \"O'nun berisinden bel bağladıklarınızı çağırın; onlar, başınızdaki zorluk ve sıkıntıyı ne kaldırabilirler ne de değiştirebilirler.\"",
  "57.	O yakarıp durduklarının kendileri, en çok yakınlık kazanmışları da dahil, Rablerine varmaya vesîle ararlar; O'nun rahmetini umarlar, O'nun azabından korkarlar. Çünkü Rabbinin azabı gerçekten korkulasıdır.",
  "58.	Hiçbir kent/medeniyet dışta kalmamak üzere, kıyamet gününden önce hepsini ya helâk edeceğiz yahut da şiddetli bir azapla azaplandıracağız. İşte bu, Kitap'ta satır satır yazılmış bulunuyor.",
  "59.	Bizi, mucizeler göstermekten alıkoyan, daha öncekilerin onları yalanlamış olmasından başka bir şey değildir. Semûd kavmine o dişi deveyi açık bir mucize olarak verdik de onunla kendilerine zulmettiler. Biz, mucizeleri yalnız korkutup sindirmek için göndeririz.",
  "60.	Hani, sana: \"Rabbin, insanları çepeçevre kuşatmıştır.\" demiştik. Sana gösterdiğimiz o rüyayı da Kur'an'da lanetlenmiş bulunan o ağacı/soyu da insanları sınamak dışında bir sebeple göndermedik. Biz onları korkutuyoruz ama bu onların kudurganlığını artırmaktan başka bir katkı sağlamıyor.",
  "61.	Hani, meleklere: \"Âdem'e secde edin!\" demiştik; onlar da secde etmişlerdi. Ama İblis secde etmemiş, şöyle demişti: \"Çamur olarak yarattığın kişiye secde mi ederim?\"",
  "62.	Yine dedi: \"Şu benden üstün kıldığına bir baksana! Yemin olsun, eğer beni kıyamet gününe kadar ertelersen, onun soyunu, pek azı hariç, hükmüm altına alacağım.\"",
  "63.	Allah buyurdu: \"Defol git! Onlardan kim sana uyarsa, cezanız cehennem olacaktır. Ne de mükemmel ceza.\"",
  "64.	\"Onlardan güç yetirdiğini sesinle yerinden oynat. Atlıların ve yayalarınla yaygara çıkarıp üzerlerine çullan. Mallarda, evlatlarda onlara ortak ol, onlara ha bire vaatte bulun.\" Şeytan onlara bir aldanıştan başka ne vaat eder ki?!",
  "65.	\"Kuşkusuz, benim kullarım üzerinde senin hiçbir sultan olmayacaktır.\" Vekil olarak Rabbin yeter.",
  "66.	Rabbiniz odur ki, lütfundan nasip arayasınız diye sizin için denizde gemiler yürütüyor. O, size karşı gerçekten çok merhametlidir.",
  "67.	Denizde size bir zorluk dokunduğunda, O'nun dışındaki tüm yalvardıklarınız ortadan kaybolur. Fakat O, sizi kurtarıp karaya çıkarınca yüz çevirirsiniz. İnsan çok nankördür.",
  "68.	Peki, kara tarafında sizi yere geçirivermesinden yahut üstünüze çakıl savuran bir kasırga göndermesinden emin misiniz? Sonra kendinize hiçbir vekil bulamazsınız.",
  "69.	Yoksa sizi bir kez daha oraya gönderip üstünüze kırıp geçiren bir fırtına salarak, inkâr ettiğinizden dolayı sizi boğmayacağından emin misiniz? Sizin adınıza, bizden bunun öcünü alacak birini de bulamazsınız.",
  "70.	Yemin olsun, biz, âdemoğullarını onur ve üstünlükle donattık, onları karada ve denizde binitlerle yükledik. Onları, güzel ve temiz rızıklarla besledik. Ve onları, yarattıklarımızın birçoğundan üstün kıldık.",
  "71.	Gün olur, insan gruplarından herbirini kendi önderiyle çağırırız. O gün kitabı kendisine sağdan verilenler, kitaplarını okuyacaklar ve bir kıl kadar haksızlığa uğratılmayacaklar.",
  "72.	Bu dünyada kör olan, âhirette de kördür. Yolca da daha sapıktır o.",
  "73.	Az kalsın seni, sana vahyettiğimizden uzaklaştırarak ondan gayrısını uydurup bize isnat edesin diye fitneye düşüreceklerdi. İşte o takdirde seni dost edinirlerdi.",
  "74.	Eğer biz seni sağlamlaştırmamış olsaydık, yemin olsun, onlara birazcık meylediverecektin.",
  "75.	İşte o zaman sana, hayatın da ölümün de katmerli acılarını tattırdık. Ve bize karşı hiçbir yardımcı da bulamazdın.",
  "76.	Az kalsın bu topraktan çıkarmak için seni sıkıştıracaklardı. Böyle bir durumda onlar orada senin arkandan çok az bir süre kalacaklardı.",
  "77.	Senden önce gönderdiğimiz resullerimize uygulanan yöntem de buydu. Sen bizim yol ve yöntemimizde değişme bulamazsın.",
  "78.	Güneşin kaymasından/aşağı sarkmasından, gecenin kararmasına kadar namazı/duayı yerine getir. Sabah Kur'an'ını da gözet. Çünkü sabah Kur'an'ı tanıklarca izlenmektedir.",
  "79.	Sana özgü bir davranış olarak, gecenin bir kısmında, o Kur'an'la meşgul olmak üzere uyanık ol/uykudan uyan. Böylece Rabbinin seni övgüye layık bir konuma ulaştırması umulur.",
  "80.	Şöyle yakar: \"Rabbim! Beni, gireceğim yere doğruluk-dürüstlükle sok, çıkacağım yerden doğruluk-dürüstlükle çıkar. Katından bana yardımcı bir güç/kanıt ver.\"",
  "81.	Ve de ki: \"Hak geldi bâtıl yıkılıp gitti. Bâtıl, yok olmaya zaten mahkûmdu.\"",
  "82.	Biz Kur'an'dan, inananlar için şifa ve rahmet olacak şeyler indiriyoruz. Ama bu, zalimlerin yıkımını artırmaktan başka katkı sağlamıyor.",
  "83.	İnsana nimet verdiğimizde yüz çevirip yan çizer. Kendisine şer dokununca da hemen ümitsiz oluverir.",
  "84.	De ki: \"Herkes, kendi varlık yapısına uygun iş görür. Yolca daha doğru gidenin kim olduğunu Rabbiniz daha iyi bilir.\"",
  "85.	Ve sana ruhtan sorarlar. De ki: \"Ruh, Rabbimin emrindendir. Ve size, ilimden sadece az bir şey verilmiştir.\"",
  "86.	Yemin olsun, biz dilesek sana vahyetmiş olduğumuzu tamamen gideriveririz, sonra onu elde etmek için bizim katımızda kendine bir vekil de bulamazsın.",
  "87.	Ancak, Rabbinden bir rahmet müstesna. Kuşkusuz, O'nun sana lütfu pek büyüktür.",
  "88.	De ki: \"Yemin olsun, eğer insanlar ve cinler şu Kur'an'ın bir benzerini getirmek üzere bir araya toplansalar, birbirlerine de destek olsalar, onun bir benzerini yine de ortaya getiremezler.\"",
  "89.	Yemin olsun, biz bu Kur'an'da, insanlar için her benzetmeden nice örnekler sıraladık. Ama insanların çoğu inkâr ve nankörlükten başka bir şeyde diretmediler.",
  "90.	Dediler ki: \"Bizim için yerden bir pınar fışkırtmadığın sürece sana asla inanmayacağız!\"",
  "91.	\"Yahut senin, hurmalardan, üzümlerden oluşan bir bahçen olmalı. Onların aralarından şarıl şarıl ırmaklar akıtmalısın.\"",
  "92.	\"Yahut iddia ettiğin gibi göğü, parçalar halinde üzerimize düşürmelisin, yahut Allah'ı ve melekleri karşımıza dikmelisin.\"",
  "93.	\"Yahut altından bir evin olmalı, yahut göğe yükselmelisin. Ancak senin göğe çıktığına, okuyacağımız bir kitabı bize indireceğin zamana kadar, asla inanmayız!\" De ki: \"Rabbimin şanı yücedir. Ben, insan bir resulden başka neyim ki?\"",
  "94.	Kendilerine hak kılavuzcusu geldiğinde, insanların iman etmelerine, şöyle demelerinden başka bir şey engel olmadı: \"Allah, bir insan mı resul gönderdi?\"",
  "95.	De ki: \"Eğer yeryüzünde doygunluğa ulaşmış melekler dolaşır olsaydı, elbette gökten onlara bir melek-resul gönderirdik.\"",
  "96.	De ki: \"Benimle sizin aranızda tanık olarak Allah yeter. O, kullarından haberdardır, onları görmektedir.\"",
  "97.	Allah kime hidayet verirse doğru olan yolu bulan odur. Kimi de şaşırtırsa, böyleleri için O'nun dışında dostlar bulamazsın. Kıyamet günü böylelerini kör, dilsiz ve sağır bir halde yüzleri üstüne sürerek haşrederiz. Varacakları yer cehennemdir ki, alevi dindikçe kızgın ateşini körükleyiveririz.",
  "98.	Cezaları işte budur. Çünkü ayetlerimizi inkâr ettiler ve şöyle dediler: \"Biz, bir kemik yığını olduktan, un-ufak hale geldikten sonra mı, sahi bundan sonra mı, yeni bir yaratılışla diriltileceğiz?\"",
  "99.	Görmediler mi ki, o, gökleri ve yeri yaratan Allah, kendilerinin benzerlerini yaratmaya da Kaadir'dir. Onlar için bir süre belirlemiştir, bunda kuşku yok. Ama zalimler, inkârdan başka bir şeyde direnmiyorlar.",
  "100.	De ki: \"Eğer Rabbimin rahmet hazinelerine sahip olsaydınız, o zaman da harcanır-biter korkusuyla cimri davranırdınız.\" İnsan çok cimridir.",
  "101.	Yemin olsun, biz, Mûsa'ya açık-seçik dokuz mucize verdik. İsrailoğullarına sor: Hani, Mûsa onlara geldiğinde Firavun ona şöyle demişti: \"Ben senin kesinlikle büyülendiğini düşünüyorum, ey Mûsa!\"",
  "102.	Mûsa dedi: \"Yemin olsun, sen bilmektesin ki, bunları, basîretle görülebilecek ibretler halinde/basîretler olarak o, göklerin ve yerin Rabbinden başkası indirmedi. Vallahi ben seni mahvolmuş görüyorum, ey Firavun!\"",
  "103.	Firavun onları o topraktan sürüp çıkarmak istedi de biz onu ve yanındakilerin tümünü boğduk.",
  "104.	Bunun ardından, İsrailoğullarına şöyle dedik: \"Şu toprakta oturun. Âhiret vaadi/ikinci vaat gelince, sizi toplayıp bir araya getireceğiz.\"",
  "105.	Biz onu hak ile indirdik ve o hak ile indi. Seni de ancak müjdeci ve uyarıcı olarak gönderdik.",
  "106.	Onu, okunacak şeyleri toplayan bir kitap/ bir Kur'an olarak, insanlara dura dura okuyasın diye kısımlara ayırıp ağır ağır indirdik.",
  "107.	De ki: \"İster inanın ona, ister inanmayın. O, kendilerine daha önce ilim verilmiş olanlara okunduğunda, onlar, çeneleri üstü secdelere kapanıyorlar.\"",
  "108.	Ve diyorlar: \"Rabbimizin şanı yücedir, Rabbimizin vaadi mutlaka gerçekleşecektir!\"",
  "109.	Ağlayarak çeneleri üstü kapanıyorlar; o onların huşûunu artırıyor.",
  "110.	De ki: \"İster Allah diye yakarın, ister Rahman diye yakarın. Hangisiyle yakarırsanız yakarın, en güzel isimler/Esmâül Hüsna O'nundur. Namazında/duanda sesini yükseltme, kısma da. İkisi ortası bir yol tut.\"",
  "111.	Şöyle de: \"Hamt, o Allah'a özgüdür ki, çocuk edinmemiştir; mülk ve yönetiminde ortağı yoktur; âcizlik yüzünden dost edinmemiştir.\" Ve tekbir edip yücelt O'nu!"
];
