final List<String> meryem = [
  "1.	Kâf, Hâ, Yâ, Ayn, Sâd.",
  "2.	Rabbinin rahmetinin, Zekeriyya kuluna anılışıdır bu...",
  "3.	Hani o, Rabbine gizli bir sesle seslenmişti de,",
  "4.	Şöyle demişti: \"Rabbim, işte karşındayım. Kemik gevşedi bende. İhtiyarlıktan başım beyaz alevle tutuştu. Sana yakarma/senin için çağrı yapma konusunda ise Rabbim, hiç bedbaht/zorluk ve şiddet yanlısı olmadım.\"",
  "5.	\"Ben, arkamdan gelecek yakınlarımdan endişe ediyorum. Karımsa kısır. O halde, katından bana bir dost bağışla;",
  "6.	Ki hem bana mirasçı olsun hem de Yakub hanedanına mirasçı olsun. Ve onu hoşnutluğunu kazanmış bir kul eyle, Rabbim.\"",
  "7.	Ey Zekeriyya! Biz sana bir oğul müjdeliyoruz; adı Yahya, daha önce ona hiç kimseyi adaş yapmadık.",
  "8.	Dedi: \"Rabbim, benim için oğul nasıl söz konusu olur? Karım, doğurganlığını yitirmiştir, bense yaşlılığın gerçekten en ileri basamağına ulaştım.\"",
  "9.	\"Bu budur.\" dedi. Rabbin şöyle buyurdu: \"Onu yapmak benim için çok kolaydır. Nitekim daha önce de sen hiçbir şey değilken seni yaratmıştım.\"",
  "10.	Dedi: \"Rabbim, bana bir işaret ver.\" Cevap verdi: \"İşaretin, sapasağlam olduğun halde üç gece insanlarla konuşmamandır.\"",
  "11.	Bunun üzerine Zekeriyya, yakarış yerinden ayrılıp halkının karşısına geçti ve onlara \"sabah-akşam tespih edin\" diye işaret verdi.",
  "12.	\"Ey Yahya! Kitap'ı kuvvetle tut.\" Biz ona daha sabi iken hikmet verdik.",
  "13.	Katımızdan bir kalp yumuşaklığı, bir temizlik verdik. Korunan biriydi o.",
  "14.	Ana-babasına iyilik eden biriydi; zorba, isyancı biri değil.",
  "15.	Selam olsun ona, doğduğu gün, öleceği gün ve diri olarak kaldırılacağı gün.",
  "16.	Kitap'ta Meryem'i de an. Hani o, ailesinden ayrılıp doğu tarafında bir mekâna çekilmişti.",
  "17.	Onlarla arasına bir perde çekmişti. Biz de ruhumuzu ona göndermiştik de o kendisine sapasağlam bir insan şeklinde görünmüştü.",
  "18.	Meryem demişti: \"Ben senden, Rahman'a sığınıyorum. Takva sahibi biriysen dikkatli ol.\"",
  "19.	Ruh dedi: \"Ben, sadece Rabbinin elçisiyim. Sana tertemiz bir oğlan bağışlamak için buradayım.\"",
  "20.	Dedi: \"Benim nasıl oğlum olur; bana herhangi bir insan dokunmadı. Ben bir kahpe de değilim.\"",
  "21.	Dedi: \"İşte böyle! Rabbin buyurdu ki: 'O benim için çok kolaydır. Böyle olması onu, insanlara bir mucize ve bizden bir rahmet yapmamız içindir. Hükme bağlanmış bir iştir bu.\"",
  "22.	Ona gebe kaldı. Ardından da onunla uzak bir mekâna çekildi.",
  "23.	Nihayet doğum sancısı onu, bir hurma ağacının kütüğüne götürdü. \"Ah dedi, keşke daha önce ölseydim, keşke unutulup gitseydim.\"",
  "24.	Altından ona şöyle seslendi: \"Tasalanma, Rabbin senin alt yanında bir su arkı vücuda getirdi.\"",
  "25.	\"Hurma ağacının kütüğünü kendine doğru salla, üzerine olgun, taze hurma dökülecektir.\"",
  "26.	\"Artık ye, iç. Gözün aydın olsun. Eğer insanlardan birini görürsen şöyle söyle: 'Ben Rahman için oruç adadım. Onun için bugün, insan cinsinden hiç kimseyle konuşmayacağım.\"",
  "27.	Meryem, onu taşıyarak toplumuna getirdi. \"Ey Meryem, dediler, şaşılacak bir iş yaptın!\"",
  "28.	\"Ey Harun'un kızkardeşi! Baban kötü bir adam değildi. Annen de bir kahpe değildi.\"",
  "29.	Meryem, çocuğa işaret etti. Dediler: \"Beşikteki bir sabiyle nasıl konuşuruz?\"",
  "30.	Sabi dedi: \"Ben Allah'ın kuluyum. O bana kitap verdi, beni peygamber yaptı.\"",
  "31.	\"Beni, bulunduğum her yerde kutsal ve bereketli kıldı. Yaşadığım sürece bana namazı/duayı, zekâtı önerdi.\"",
  "32.	\"Anneme iyilik etmemi önerdi. Beni zorba bir eşkıya yapmadı.\"",
  "33.	\"Selam bana doğduğum gün, öleceğim gün ve diri olarak kaldırılacağım gün.\"",
  "34.	İşte Meryem'in oğlu İsa budur! Hakkında kuşku ve çelişmeye düştükleri şeyin doğrusu bu sözdür.",
  "35.	Bir oğul edinmek Allah'a asla yakışmaz. O'nun şanı yücedir. Bir iş ve oluşa karar verdi mi, ona sadece \"Ol!\" der, o hemen oluverir.",
  "36.	Şüphesiz, Allah, benim de Rabbimdir, sizin de Rabbinizdir. O halde O'na ibadet edin. Dosdoğru yol budur.",
  "37.	Kendi aralarından çıkan hizipler ihtilafa düştüler. Büyük bir günün tanıklığından ötürü vay o inkârcıların haline!",
  "38.	Bize gelecekleri gün neler işitecekler, neler görecekler! Fakat o zalimler bugün, açık bir sapıklık içindedirler.",
  "39.	Sen onları, o hasret günü ile ilgili olarak uyar. Çünkü onlar gaflet içindeyken, iman da etmemişken iş bitirilmiş olacaktır.",
  "40.	Yeryüzüne ve üzerindekilere biz mirasçı olacağız, biz! Ve bize döndürülecekler.",
  "41.	Kitap'ta İbrahim'i de an. O, özü-sözü doğru bir peygamberdi.",
  "42.	Hani, babasına demişti ki: \"Babacığım; işitmeyen, görmeyen, sana hiçbir yarar sağlamayan şeylere niçin kulluk ediyorsun?\"",
  "43.	\"Babacığım, bana ilimden, sana ulaşmayan bir nasip geldi. O halde bana uy ki, seni düzgün bir yola ileteyim!\"",
  "44.	\"Babacığım, şeytana kulluk etme! Çünkü şeytan Rahman'a isyan etmişti.\"",
  "45.	\"Babacığım, ben sana Rahman'dan bir azap dokunmasından, böylece şeytanın dostu haline gelmenden korkuyorum!\"",
  "46.	Babası dedi: \"Sen benim ilahlarımdan yüz mü çeviriyorsun ey İbrahim! Eğer bu işe son vermezsen, vallahi seni taşlarım! Uzun bir süre uzak kal benden!\"",
  "47.	Dedi: \"Selam sana! Senin için Rabbimden af dileyeceğim. Çünkü O, bana karşı çok lütufkârdır.\"",
  "48.	\"Sizden de Allah dışındaki yakardıklarınızdan da ayrılıyorum; Rabbime dua edeceğim. Umarım, Rabbime yakarışımla/Rabbim için çağrımda bahtsızlığa/eşkıyalığa düşmem.\"",
  "49.	İbrahim, onlardan ve Allah dışında kulluk ettiklerinden uzaklaşınca, ona İshak'ı ve Yakub'u bağışladık ve hepsini peygamber yaptık.",
  "50.	Onlara, rahmetimizden nimetler bağışladık. Ve kendileri için yüksek bir doğruluk dili oluşturduk.",
  "51.	Kitap'ta Mûsa'yı da an. Çünkü o, içtenlik ve dürüstlüğe erdirilmişti ve o bir resul, bir peygamberdi.",
  "52.	Ona Tûr'un sağ tarafından seslendik. Onu, fısıldaşan kimse kadar yaklaştırdık.",
  "53.	Rahmetimizden ona kardeşi Hârun'u bir peygamber olarak armağan ettik.",
  "54.	Kitap'ta İsmail'i de an. Çünkü o, vaadinde sadıktı; bir resuldü, bir peygamberdi.",
  "55.	Ailesine namazı/duayı, zekâtı emrederdi. Rabbi katında hoşnutluk kazanmış bir kişiydi.",
  "56.	Kitap'ta İdris'i de an. Çünkü o, özü-sözü tam uyuşan bir kişiydi, bir peygamberdi.",
  "57.	Onu yüce bir mekâna yükselttik.",
  "58.	İşte bunlar, Allah'ın kendilerine nimet lütfettiği peygamberlerdendir: Âdem'in soyundan, Nûh'la birlikte taşıdıklarımızdan, İbrahim ve İsrail'in soyundan, kılavuzluk edip seçtiğimiz kimselerden. Kendilerine Rahman'ın ayetleri okunduğunda, ağlayarak secdelere kapanırlardı.",
  "59.	Ama arkalarından öyle bir nesil geldi ki; namazı/duayı yitirdiler, şehvetlere uydular. Bunlar, azgınlıklarının cezasını bulacaklardır.",
  "60.	Tövbe eden, iman edip hayra ve barışa yönelik iyi iş yapan müstesna. Böyleleri cennete girecekler ve hiçbir şekilde haksızlığa uğratılmayacaklar.",
  "61.	Rahman'ın, kullarına gaybda vaat ettiği Adn cennetlerine girecekler. Kuşkusuz, O'nun vaadi yerine gelir.",
  "62.	Orada boş lakırdı değil, yalnızca \"selam\" işitirler. Orada kendilerinin sabah, akşam, rızıkları da hazırdır.",
  "63.	Kullarımızdan takva sahibi olanları mirasçı yapacağımız cennet işte budur.",
  "64.	Biz sadece Rabbinin emrini indiririz/biz ancak Rabbinin emriyle ineriz. Önümüzdeki, arkamızdaki ve bunlar arasındaki herşey O'nundur. Rabbin asla unutkan değildir.",
  "65.	Göklerin, yerin ve bunlar arasındaki şeylerin Rabbidir o. O'na ibadet et ve O'na ibadette sabırlı ol. O'na adaş olacak birini biliyor musun?",
  "66.	Diyor ki insan: \"Öldüğüm zaman diri olarak tekrar çıkarılacak mıyım?\"",
  "67.	Hatırlamıyor mu insan; o daha önce hiçbir şey değilken, onu biz yarattık.",
  "68.	Rabbine yemin olsun ki; onları da, şeytanları da mutlaka haşredeceğiz, sonra hepsini diz çökmüş halde cehennemin çevresinde hazır bulunduracağız.",
  "69.	Sonra her gruptan, Rahman'a karşı kafa tutmada daha şiddetli davrananlar kimlerse, onları ayıracağız.",
  "70.	Elbette ki biz, oraya girmeye daha layık olanların kimler oldğunu herkesten iyi biliriz.",
  "71.	İçinizden oraya uğramayacak hiç kimse yoktur. Bu, Rabbin üzerinde kesinleşmiş bir hükümdür.",
  "72.	Sonra biz, korunup sakınanları kurtaracağız. Zalimleri de orada dizleri üzerinde çökmüş bırakacağız.",
  "73.	Onlara ayetlerimiz açık-seçik okunduğunda, inkâr edenler inananlara şöyle derler: \"İki zümreden hangisi makamca daha üstün, meclisce daha güzel?\"",
  "74.	Onlardan önce nice kuşaklar helak ettik ki, malca ve manzaraca daha alımlıydılar.",
  "75.	De ki: \"Her kim sapıklıkta ise Rahman ona iyice süre versin. Nihayet, kendilerine vaat edileni, azabı veya kıyametin kopuşunu gördüklerinde mekânca daha kötü, taraflarca daha zayıf olanın kim olduğunu bilecekler.\"",
  "76.	Allah, doğru yolda olanların hidayetini artırır. Barışa ve hayra yönelik kalıcı işler, Rabbin katında sevapça daha üstün, sonuç bakımından daha hayırlıdır.",
  "77.	Ayetlerimizi inkâr edip, \"Bana mal da evlat da kesinlikle verilecek.\" diyeni gördün mü?",
  "78.	Bu adam gaybı mı öğrendi, yoksa Rahman katında bir söz mü aldı?",
  "79.	Hayır, hayır! Biz onun söylediğini yazacağız ve onun için azabı uzattıkça uzatacağız.",
  "80.	O dediklerine biz vâris olacağız. Kendisi bir başına bize gelecek.",
  "81.	Kendilerine onur ve destek olsunlar diye Allah dışında ilahlar edindiler.",
  "82.	Hayır, hayır! Onlar, onların ibadetlerini inkâr edecekler ve onların aleyhinde düşman kesilecekler.",
  "83.	Görmedin mi biz, şeytanları inkârcıların üzerine salmışız da onları oynatıp kıvırttırıyorlar.",
  "84.	Onlar için acele etme. Biz onlar için günleri teker teker sayıyoruz.",
  "85.	Gün olur, o sakınanları biz, Rahman'ın huzurunda heyet halinde toplarız.",
  "86.	Suçluları da susuz ve yaya olarak cehenneme sevk ederiz.",
  "87.	Rahman katında söz almış olandan başkaları şefaat imkânı bulamazlar.",
  "88.	\"Rahman çocuk edindi.\" dediler.",
  "89.	Yemin olsun ki siz, çok çirkin bir iddiada bulundunuz.",
  "90.	Bu söz yüzünden neredeyse gökler çatlayacak, yer parçalanacak, dağlar yıkılıp çökecek;",
  "91.	Rahman için çocuk iddia ettiklerinden ötürü.",
  "92.	Rahman'a çocuk edinmek yakışmaz.",
  "93.	Göklerde ve yerde bulunan herkes, Rahman'a kul olarak gelecektir.",
  "94.	Yemin olsun, O onların hepsini kuşatmış ve tamamını tek tek saymıştır.",
  "95.	Ve onların hepsi kıyamet günü O'na tek tek gelecektir.",
  "96.	İman edip hayra ve barışa yönelik işler yapanlara gelince, Rahman onlar için bir sevgi oluşturacaktır.",
  "97.	Biz onu; senin dilinle kolaylaştırdık ki, sakınanları onunla müjdeleyesin, inatçı bir kavmi de onunla uyarasın.",
  "98.	Biz onlardan önce de nice kuşaklar helâk ettik. Onlardan herhangi birini hissediyor musun, yahut onların bir iniltisini duyuyor musun?"
];
